### ISSUE TITLE
SMP incompatible when casting spells?

### ISSUE THREAD

**Issue by LemADEC** [Tamaized/Dal-Quor#233]
As of VoidCraft-1.12-0.26.10 + TamModized-1.12.1-0.15.5, when trying to cast a spell with right click, console is reporting an exception, trying to use client side I18n at VadeMecumWordsOfPower.java:127

```
[21:07:18] [Server thread/FATAL] [VF]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
>       at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
>       at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
>       at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
>       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3364]
>       at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3963) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) [nz.class:?]
>       at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
>       at tamaized.voidcraft.common.vademecum.progression.VadeMecumWordsOfPower.invoke(VadeMecumWordsOfPower.java:127) ~[VadeMecumWordsOfPower.class:?]
>       at tamaized.voidcraft.common.items.VadeMecum.dorightClick(VadeMecum.java:111) ~[VadeMecum.class:?]
>       at tamaized.voidcraft.common.items.VadeMecum.onItemRightClick(VadeMecum.java:97) ~[VadeMecum.class:?]
>       at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:217) ~[aip.class:?]
>       at net.minecraft.server.management.PlayerInteractionManager.processRightClick(PlayerInteractionManager.java:358) ~[or.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.processTryUseItem(NetHandlerPlayServer.java:763) ~[pa.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:32) ~[mb.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:9) ~[mb.class:?]
>       at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:92) ~[PacketUtil.class:1.12.2-2705-7.1.0-BETA-3364]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zle000(SourceFile:539) ~[hv$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
>       at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
>       ... 7 more
```

**Comment by Tamaized** [comment]
Not a sponge issue, it's my end.
